name: Get AWS Secrets Manager Values

on:
  push:
    branches:
      - main

jobs:
  get_secrets_manager_values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Get AWS Secrets Manager secret value
        id: get_secret
        run: |
          SECRET_NAME="centrae_staging"  # Reemplaza con el nombre de tu secreto
          SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id $SECRET_NAME --output json)
          SECRET_KEY_VALUE=$(echo "$SECRET_JSON" | jq -r '.SecretString | to_entries[] | "\(.key)=\(.value)"' | tr '\n' '\n')
          echo "$SECRET_VALUE" > $GITHUB_WORKSPACE/secret_values.json

      - name: Show secret JSON
        run: |
          cat $GITHUB_WORKSPACE/secret_values.json
