name: Get AWS Secrets Manager Values

on:
  push:
    branches:
      - main

jobs:
  get_secrets_manager_values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get AWS Secrets Manager secret value
        id: get_secret
        run: |
          SECRET_NAME="centrae_staging"  # Reemplaza con el nombre de tu secreto
          SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id $SECRET_NAME --output json | jq -r .SecretString)
          echo "$SECRET_VALUE" > $GITHUB_WORKSPACE/secret_values.txt

      - name: Show secret values
        run: |
          cat $GITHUB_WORKSPACE/secret_values.txt

      - name: Commit secret values file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $GITHUB_WORKSPACE/secret_values.txt
          git commit -m "Add secret values file"
          git push
